apiVersion: dp.wso2.com/v1alpha1
kind: API
metadata:
  name: product-api
  namespace: argocd
spec:
  apiName: ProductAPI
  apiVersion: 1.0.0
  apiType: REST
  basePath: /products/1.0.0
  organization: default
  definition:
    inline:
      openAPISpec: |
        openapi: 3.0.1
        info:
          title: Product API
          version: 1.0.0
        paths:
          /products:
            get:
              summary: List all available products
              responses:
                "200":
                  description: OK
  endpointConfigurations:
    production:
      type: REST
      url: https://run.mocky.io/v3/5185415ba171ea3a00704eed
    sandbox:
      type: REST
      url: https://run.mocky.io/v3/5185415ba171ea3a00704eed
  mode: privateJet
