apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-api
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: wso2-apim
  source:
    repoURL: https://github.com/Tharanidk/wso2-api-gitops
    targetRevision: main
    path: prod
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
